### ISSUE TITLE
Bug: waypoint is not updated

### ISSUE THREAD

**Issue by kennyfong19931** [hkbus/route-waypoints#2]
- 見你呢度 [12月](https://github.com/kennyfong19931/siri-shortcut-hk-bus-eta/commit/71b77972da77f11eb614b439408bed6786059475) data 無 update
Crawling 條 download link 唔可以 hardcode, 要去 [Metadata](https://portal.csdi.gov.hk/csdi-webpage/metadata/td_rcd_1638844988873_41214) 入面搵最新嗰條 link
- Readme CSDI 條 link 錯咗, 而家會見到空白頁/上次睇過嘅 dataset, 應該用 [https://portal.csdi.gov.hk/geoportal/?lang=zh-hk&datasetId=td_rcd_1638844988873_41214](https://portal.csdi.gov.hk/geoportal/?lang=zh-hk&datasetId=td_rcd_1638844988873_41214)

**Comment by chunlaw** [comment]
fixed in the latest commit #3462f0e5bc554f6e0a858e835f6e3f2f6398b00c
